<?php

use Illuminate\Database\Seeder;

class KategoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mKategori')->insert([
        	[
                'id' =>1,
                'namaKategori' => 'UGD',
                'status' => 1,
                'idGroupKategori' => '3',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC002',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
           	[
                'id' =>2,
                'namaKategori' => 'RUANG VK',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC003',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>3,
                'namaKategori' => 'RUANG OK',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC004',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>4,
                'namaKategori' => 'RAWAT INAP LANTAI II',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC062',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>5,
                'namaKategori' => 'RAWAT INAP LANTAI III',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC063',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>6,
                'namaKategori' => 'RAWAT INAP LANTAI IV',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC064',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>7,
                'namaKategori' => 'NICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC065',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>8,
                'namaKategori' => 'PICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC066',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>9,
                'namaKategori' => 'RESTI',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC068',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>10,
                'namaKategori' => 'INTERMEDIATE',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC069',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>11,
                'namaKategori' => 'RUANG BAYI',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC070',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>12,
                'namaKategori' => 'Suite Sita',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'10',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>13,
                'namaKategori' => 'VIP Exc Kunti',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'11',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>14,
                'namaKategori' => 'Super Vip Supraba',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'12',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>15,
                'namaKategori' => 'Kelas Kausalya',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'13',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>16,
                'namaKategori' => 'Kelas Shakuntala',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'14',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>17,
                'namaKategori' => 'Ruang Transisi',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'15',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>18,
                'namaKategori' => 'ICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'16',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>19,
                'namaKategori' => 'Kelas Madri',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'17',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>20,
                'namaKategori' => 'Kelas Srikandi',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'18',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>21,
                'namaKategori' => 'NICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'24',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>22,
                'namaKategori' => 'PICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'25',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>23,
                'namaKategori' => 'Intermediate NICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'26',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>24,
                'namaKategori' => 'Intermediate (ICU)',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'23',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>25,
                'namaKategori' => 'Intermediate PICU',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'27',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>26,
                'namaKategori' => 'K. Bayi',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'91',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>27,
                'namaKategori' => 'Resti',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'92',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>28,
                'namaKategori' => 'INTERMEDIATE',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'93',
                'isKamar' => 1,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>29,
                'namaKategori' => 'POLI UMUM',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC007',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>30,
                'namaKategori' => 'POLI SPESIALIS KANDUNGAN & KEBIDANAN',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC008',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>31,
                'namaKategori' => 'POLI SPESIALIS ANAK',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC009',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>32,
                'namaKategori' => 'POLI PHYSIOTHERAPY',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC010',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>33,
                'namaKategori' => 'LAKTASI',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC011',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>34,
                'namaKategori' => 'POLI SPESIALIS BEDAH ANAK',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC014',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>35,
                'namaKategori' => 'ECHOCARDIOGRAPHY',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0008',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>36,
                'namaKategori' => 'RADIOLOGI',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0014',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>37,
                'namaKategori' => 'Andrologi',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0018',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>38,
                'namaKategori' => 'KLINIK REPRODUKSI',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0019',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>39,
                'namaKategori' => 'Lab WIN',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0020',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>40,
                'namaKategori' => 'R Tumbuh Kembang',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0022',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>41,
                'namaKategori' => 'LABORATORIUM',
                'status' => 1,
                'idGroupKategori' => '5',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC005',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>42,
                'namaKategori' => 'BABY SPA',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC012',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>43,
                'namaKategori' => 'POLI INTERNA',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0017',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>44,
                'namaKategori' => 'PAKET',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SECT0021',
                'isKamar' => 0,
                'isSection' => 1,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>45,
                'namaKategori' => 'Pasien Baru RJ',
                'status' => 1,
                'idGroupKategori' => '7',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 1,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>46,
                'namaKategori' => 'Pasien Baru RI',
                'status' => 1,
                'idGroupKategori' => '7',
                'addBySystem' => 1,
                'idSyncToSanata' =>'1',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 1,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>47,
                'namaKategori' => 'Pasien Repeater RI',
                'status' => 1,
                'idGroupKategori' => '7',
                'addBySystem' => 1,
                'idSyncToSanata' =>'1',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 1,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>48,
                'namaKategori' => 'Pasien Repeater RJ',
                'status' => 1,
                'idGroupKategori' => '7',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 1,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>49,
                'namaKategori' => 'Rawat Jalan',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>50,
                'namaKategori' => 'Rawat Inap',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>51,
                'namaKategori' => 'Rawat Darurat',
                'status' => 1,
                'idGroupKategori' => '3',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>52,
                'namaKategori' => 'Obat Bebas',
                'status' => 1,
                'idGroupKategori' => '1',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>53,
                'namaKategori' => 'Tata Boga',
                'status' => 1,
                'idGroupKategori' => '2',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>54,
                'namaKategori' => 'Diskon',
                'status' => 1,
                'idGroupKategori' => '9',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>55,
                'namaKategori' => 'Ruang OK',
                'status' => 1,
                'idGroupKategori' => '10',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC004',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>56,
                'namaKategori' => 'Ruang VK',
                'status' => 1,
                'idGroupKategori' => '10',
                'addBySystem' => 1,
                'idSyncToSanata' =>'SEC003',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>57,
                'namaKategori' => 'Tambahan Lainnya',
                'status' => 1,
                'idGroupKategori' => '9',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>58,
                'namaKategori' => 'Total Pendapatan',
                'status' => 1,
                'idGroupKategori' => '11',
                'addBySystem' => 1,
                'idSyncToSanata' =>'0',
                'isKamar' => 0,
                'isSection' => 0,
                'isPasien' => 0,
                'isPasienRepeater' => 0,
                'isPaket' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ]
		]);
    }
}
